<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitab30dd02396bab4ef3a75171dd5e6a18
{
    public static $files = array (
        'd05ecc14ff93fd612a81ec7e8ab4c2c9' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v5p4.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Segment\\' => 8,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Segment\\' => 
        array (
            0 => __DIR__ . '/..' . '/segmentio/analytics-php/lib',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab30dd02396bab4ef3a75171dd5e6a18::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab30dd02396bab4ef3a75171dd5e6a18::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitab30dd02396bab4ef3a75171dd5e6a18::$classMap;

        }, null, ClassLoader::class);
    }
}
