<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit82420ca694a00586932bd39f3d207417
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Segment\\Test\\' => 13,
            'Segment\\' => 8,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Segment\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/segmentio/analytics-php/test',
        ),
        'Segment\\' => 
        array (
            0 => __DIR__ . '/..' . '/segmentio/analytics-php/lib',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit82420ca694a00586932bd39f3d207417::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit82420ca694a00586932bd39f3d207417::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit82420ca694a00586932bd39f3d207417::$classMap;

        }, null, ClassLoader::class);
    }
}
