<?php return array(
    'root' => array(
        'name' => 'alquemie/cdp-analytics',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '57bfedfebe68fb1d2aa19f582deb60c5b0fcaac6',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'alquemie/cdp-analytics' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '57bfedfebe68fb1d2aa19f582deb60c5b0fcaac6',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'c29dc4b93137acb82734f672c37e029dfbd95b35',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roave/security-advisories' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '881e474a47f9a34cf1768eabe1c88932875c4874',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'segmentio/analytics-php' => array(
            'pretty_version' => '3.8.0',
            'version' => '3.8.0.0',
            'reference' => '22882f89322b8b110ca449ad1c1425a99dad6bcc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../segmentio/analytics-php',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'woocommerce/action-scheduler' => array(
            'pretty_version' => '3.7.2',
            'version' => '3.7.2.0',
            'reference' => 'cb3c7854b31a285b46964931425fef6f485be145',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../woocommerce/action-scheduler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yahnis-elsts/plugin-update-checker' => array(
            'pretty_version' => 'v5.4',
            'version' => '5.4.0.0',
            'reference' => 'e8e53e6d98e37fa7c895c93417f52e3775494715',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/plugin-update-checker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
