<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'c0e075c62109347f175d30b8d9d04c41d5153cac',
        'name' => 'alquemie/cdp-analytics',
        'dev' => true,
    ),
    'versions' => array(
        'alquemie/cdp-analytics' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'c0e075c62109347f175d30b8d9d04c41d5153cac',
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'reference' => 'c29dc4b93137acb82734f672c37e029dfbd95b35',
            'dev_requirement' => false,
        ),
        'qriouslad/codestar-framework' => array(
            'pretty_version' => 'v2.2.8.1',
            'version' => '2.2.8.1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../qriouslad/codestar-framework',
            'aliases' => array(),
            'reference' => '715d17045008833eada8d7bddabd3363326094fa',
            'dev_requirement' => false,
        ),
        'roave/security-advisories' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'reference' => '891ecbb72eac808c80fb97f2cce67824e94e5652',
            'dev_requirement' => true,
        ),
        'segmentio/analytics-php' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../segmentio/analytics-php',
            'aliases' => array(),
            'reference' => '2ed390d1c1e03328f3d5b6c43a72a4ce6a8e7f85',
            'dev_requirement' => false,
        ),
        'woocommerce/action-scheduler' => array(
            'pretty_version' => '3.5.3',
            'version' => '3.5.3.0',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../plugins/action-scheduler',
            'aliases' => array(),
            'reference' => '63ef5af013ca3a6efdd8ef8e9363ac70778713cb',
            'dev_requirement' => false,
        ),
        'yahnis-elsts/plugin-update-checker' => array(
            'pretty_version' => 'v5.0',
            'version' => '5.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/plugin-update-checker',
            'aliases' => array(),
            'reference' => '81be284da76f12c8751b477b2a0fa44364d26f84',
            'dev_requirement' => false,
        ),
    ),
);
