<?php return array(
    'root' => array(
        'name' => 'alquemie/cdp-analytics',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '10f906612fc3381ab72313dd5505fd317b4fa674',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'alquemie/cdp-analytics' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '10f906612fc3381ab72313dd5505fd317b4fa674',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'c29dc4b93137acb82734f672c37e029dfbd95b35',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roave/security-advisories' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'c4ccfdab77bd92444c6a2f7813bc20f29dbb9d13',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'segmentio/analytics-php' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => '2ed390d1c1e03328f3d5b6c43a72a4ce6a8e7f85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../segmentio/analytics-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
